app/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('signup/', views.register, name='register'),
    path('makeVideo/', views.postVideo, name='postVideo'),
    path('watch/<int:pk>', views.watchVideo, name='watch'),
    path('account/<int:pk>/', views.account, name='account'),
    path('like-video/', views.like_video, name="like-video"),
    path('TODO/', views.TODO, name='TODO'),
    path('cornhub/', views.cornhub, name='cornhub'),
    path('makePost/', views.makePost, name='makePost'),
    path('search/', views.search, name='search'),
    path('post/<int:pk>/', views.viewPost, name='post'),
    path('mdHelp/', views.mdHelp, name='mdHelp'),
    path('EconProject/', views.EconProject, name="EconProject"),
    path('follow-user/', views.follow_user, name="follow-user"),
    path('following/', views.following, name="following"),
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bugs/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'bugs'

urlpatterns = [
    path('', views.bug_report, name='bugReport'),
    path('reports/', views.bug_reportIndex, name="bugReportIndex"),
    path('view/<int:pk>', views.bugView, name="bugView"),
    path('resolve/', views.resolveBug, name="resolveBug"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

yubtub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('chat/', include('chat.urls')),
    path('jsTest/', include('jsTests.urls')),
    path('settings/', include('accounts.urls')),
    path('bug/', include('bugs.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler405 = 'app.views.handler405'

bugs/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
TYPE_CHOICES = {
    'BUG': 'Bug',
    'DOCS': 'Documentation',
    'NEW': 'Enhancement',
    'HUH?': 'Question',
}

class BugReport(models.Model):
    author = models.CharField(max_length=100, default='admin')
    title = models.CharField(max_length=255)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now=True, auto_now_add=False)
    type = models.CharField(choices=TYPE_CHOICES, max_length=50, default='BUG')
    github_issue = models.CharField(max_length=100, blank=True, null=True)
    has_github_issue = models.BooleanField(default=False)
    resolved = models.BooleanField(default=False)

    def __str__(self):
        return self.title

bugs/forms.py
from django import forms
from bugs.models import BugReport
from django.contrib.auth import get_user_model
User = get_user_model()

class BugReportForm(forms.ModelForm):
    class Meta:
        model = BugReport
        fields = ['title', 'body', 'type', 'github_issue']

bugs/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model
from django.shortcuts import redirect
from django.views.decorators.http import require_POST

from bugs.forms import BugReportForm
from bugs.models import BugReport

from itertools import chain
from operator import attrgetter

from app import mail

import json

User = get_user_model()
# Create your views here.

def bug_report(request):
    if request.method == "POST":
        form = BugReportForm(request.POST)
        if form.is_valid():
            if not request.user.is_authenticated:
                username=1
            else:
                username=request.user.id
            bug = BugReport(
                author=username,
                title=form.cleaned_data["title"],
                body=form.cleaned_data["body"],
                type=form.cleaned_data["type"],
                github_issue=form.cleaned_data["github_issue"]
            )
            if bug.github_issue != None:
                bug.has_github_issue = True
            bug.save()
            return redirect('app:index')
    else:
        form = BugReportForm()
    context = {
        'form': form
    }
    return render(request, "bugs/bugReport.html", context)

def bug_reportIndex(request):
    bugs = BugReport.objects.order_by('created_on').order_by('-created_on').filter(resolved=False)
    resolvedBugs = BugReport.objects.order_by('created_on').filter(resolved=True)
    
    combined = bugs | resolvedBugs

    authors = {}
    for i in combined:
          user = User.objects.get(id=i.author).username
          authors[i.author] = user

    context = {
         'resolvedBugs': resolvedBugs,
         'bugs': bugs,
         'authors': authors
    }
    return render(request, 'bugs/bugReportIndex.html', context)

def bugView(request, pk):
    bug = get_object_or_404(BugReport, pk=pk)
    username = User.objects.get(id=bug.author).username

    context = {
        'bug': bug,
        'username': username
    }

    return render(request, 'bugs/bugView.html', context)

@require_POST
def resolveBug(request):
	if not request.user.is_authenticated:
		return JsonResponse({'message': 'Login required'}, status=403)

	try:
		data = json.loads(request.body)
	except json.JSONDecodeError:
		return JsonResponse({'message': 'Invalid JSON'}, status=400)


	bug=data.get('bug')

	try:
		bug = BugReport.objects.get(pk=bug)
	except User.DoesNotExist:
		return JsonResponse({'message': 'User not found.'}, status=404)

	if bug.resolved:
		bug.resolved = False
		bug.save()
		return JsonResponse({'message': 'Opened bug'})
	else:
		bug.resolved = True
		bug.save()
		return JsonResponse({'message': 'Bug Resolved'})

bugs/templates/bugs/bugReport.html
{% extends "base.html" %}

{% block page_content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        Type: {{ form.type }}
    </div>
    <div>
        Title: {{ form.title }}
    </div>
    <div>
        {{ form.body }}<br>
    <small><a href="{% url 'app:mdHelp' %}">Markdown</a> is supported!</small>
    </div>
    <div>
        <p>For a better chance of us fixing it, go create a <a href="https://github.com/ExcessMarrow773/yubtub/issues/new">Github Issue</a> and put a link to it here.</p>
        {{ form.github_issue }}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <a href="{% url 'app:index' %}">Cancel</a>
</form>

{% endblock page_content %}

bugs/templates/bugs/bugReportIndex.html
{% extends "base.html" %}
{% load markdown_truncate dict_extras %}

{% block title %}YubTub - Bugs{% endblock title %}

{% block page_content %}

{% if bugs %}
<div class="video-grid" id="bugs">
    {% for bug in bugs %}
        <div class="post-card">
            <div class="post-card-label">{{ bug.get_type_display }} - <u>{{ authors | get_item:bug.author }}</u></div>

            <a href="{% url 'bugs:bugView' bug.pk %}">
                <strong>{{ bug.title.capitalize }}</strong>
            </a>
            <p>{{ bug.body | markdown_truncate:100 }}</p>
            <small>{{bug.created_on}}</small>
        </div>
    {% endfor %}
</div>
{% endif %}

{% if resolvedBugs %}
<div style="margin-top: 50rm">
<h3>Resolved</h3><hr>
<div class="video-grid" id="resolvedBugs">
    {% for bug in resolvedBugs %}
        <div class="post-card">
            <div class="post-card-label">{{ bug.get_type_display }} - <u>{{ authors | get_item:bug.author }}</u></div>

            <a href="{% url 'bugs:bugView' bug.pk %}">
                <strong>{{ bug.title.capitalize }}</strong>
            </a>
            <p>{{ bug.body | markdown_truncate:100 }}</p>
            <small>{{bug.created_on}}</small>
        </div>
    {% endfor %}
</div>
</div>
{% endif %}



{% endblock page_content %}

bugs/templates/bugs/bugView.html
{% extends "base.html" %}
{% load markdown_extras %}


{% block page_title %}
    <h2>{{ bug.title.capitalize }}</h2>
{% endblock page_title %}

{% block page_content %}
    <div class="bug-card">
        <div class="bug-card-label">{{ bug.get_type_display }} - <u>{{ username }}</u></div>
        <small>
            {{ bug.created_on.date }} at {{ bug.created_on.time }}
        </small>
        <p>
            By <a href="{% url 'app:account' bug.author %}">{{ username }}</a>
        </p>

        <p>{{ bug.body | markdown }}</p>

        {% if bug.github_issue %}
            <a href="{{ bug.github_issue }}"><h3>{{bug.github_issue}}</h3></a>
        {% endif %}
    </div>
    <button id="follow-button" onclick="resolveBug({{ bug.id }}, '{% url 'bugs:bugReportIndex' %}')">
        {% if bug.resolved %}Reopen{% else %}Resolve{% endif %}
    </button>
{% endblock page_content %}