accounts/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'accounts'

urlpatterns = [
    path('', views.settings, name='settings'),
    path('changeUsername/', views.settings, name='changeUsername'),
    path('changePassword/', views.settings, name='changePassword'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('signup/', views.register, name='register'),
    path('makeVideo/', views.postVideo, name='postVideo'),
    path('watch/<int:pk>', views.watchVideo, name='watch'),
    path('account/<int:pk>/', views.account, name='account'),
    path('like-video/', views.like_video, name="like-video"),
    path('TODO/', views.TODO, name='TODO'),
    path('cornhub/', views.cornhub, name='cornhub'),
    path('makePost/', views.makePost, name='makePost'),
    path('search/', views.search, name='search'),
    path('post/<int:pk>/', views.viewPost, name='post'),
    path('mdHelp/', views.mdHelp, name='mdHelp'),
    path('EconProject/', views.EconProject, name="EconProject"),
    path('follow-user/', views.follow_user, name="follow-user"),
    path('following/', views.following, name="following"),
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chat/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('send-message/', views.sendMsg, name="sendMsg"),
    path('<str:account>', views.chat, name='chat'),
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

yubtub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('chat/', include('chat.urls')),
    path('jsTest/', include('jsTests.urls')),
    path('settings/', include('accounts.urls')),
    path('bug/', include('bugs.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler405 = 'app.views.handler405'

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core import validators
from django.utils.translation import gettext_lazy as _

# Create your models here.

class CustomUsernameValidator(UnicodeUsernameValidator):
    regex = r'^[\w+-]+$'  # Modify this regex to allow/disallow characters
    message = _(
        'Enter a valid username. This value may contain only letters, '
        'numbers, and ./-/_ characters.'
    )

class CustomUser(AbstractUser):
	username_validator = CustomUsernameValidator()

	following = models.ManyToManyField('self', symmetrical=False, related_name='followers', blank=True)

	username = models.CharField(
        max_length=150,
        unique=True,
        validators=[username_validator],
		help_text=_(
            'Required. 150 characters or fewer. Letters, digits and +/-/_ only.'
        ),
    )

	def follow(self, user):
		self.following.add(user)

	def unfollow(self, user):
		self.following.remove(user)

	def follower_count(self):
		return len(self.followers.all())

	def is_following(self, user):
		return self.following.filter(pk=user.pk).exists()

	def is_followed_by(self, user):
		return self.followers.filter(pk=user.pk).exists()

accounts/forms.py
from django import forms
from django.contrib.admin.widgets import AdminSplitDateTime
from django.utils import timezone
from accounts.models import CustomUser
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm

User = get_user_model()

class ProfileDetailsChange(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

class ProfileUsernameChange(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']

class ProfilePasswordChange(PasswordChangeForm):
    user = User

accounts/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model, login
from django.shortcuts import redirect
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from .forms import ProfileDetailsChange, ProfilePasswordChange, ProfileUsernameChange


from itertools import chain
from operator import attrgetter
import os
import json

User = get_user_model()

# Create your views here.


@login_required(login_url='/login/')
def settings(request):
	print(request.POST)
	userModel = get_object_or_404(User, username=request.user.username)

	if request.method == "POST":
		if 'changeUsername/' in request.path:
			form = ProfileUsernameChange(request.POST, instance=userModel)
		elif 'changePassword/' in request.path:
			form = ProfilePasswordChange(user=request.user, data=request.POST)
		else:
			form = ProfileDetailsChange(request.POST, request.FILES, instance=userModel)
		if form.is_valid():
			form.save()
			return redirect('accounts:settings')
	else:
		if 'changeUsername/' in request.path:
			form = ProfileUsernameChange(instance=userModel)
		elif 'changePassword/' in request.path:
			form = ProfilePasswordChange(user=request.user)
		else:
			form = ProfileDetailsChange(instance=userModel)

	context = {'form': form, 'mymodel_instance': userModel}

	return render(request, 'accounts/settings.html', context)

app/templates/app/TODO.html
{% extends 'base.html' %}
{% load markdown_extras %}

{% block page_content %}
{{ TODO | markdown}}
{% endblock page_content %}

app/templates/app/account.html
{% extends "base.html" %}
{% load static %}
{% load markdown_truncate markdown_extras dict_extras %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/widgets.css' %}">
    <script src="{% static 'admin/js/core.js' %}"></script>
    <script>
        console.log("{{ username.lower }}")
        console.log("{{ username.upper }}")
        console.log("{{ username }}")
    </script>
{% endblock extra_head %}

{% block heading %}
    {{ username }}'s stuff
    {% if not isUsersAccount and user.is_authenticated %}
        <button id="follow-button" data-account="{{ username }}" onclick="followUser()">
            {% if followingUser %}Unfollow{% else %}Follow{% endif %}
        </button>
    {% endif %}
{% endblock heading %}

{% block extra_navbar %}
    <a href="{% url 'accounts:settings' %}" class="button">Settings</a>
{% endblock extra_navbar %}

{% block page_content %}
<hr>
<p id="follow-response"></p>


    {% if combined %}
    <div class="video-grid">
        {% for thing in combined %}

            {% if thing.type == "video" %}
                <div class="video-card">
                    <a href="{% url 'app:watch' thing.id %}">
                        <img src="{{ thing.thumbnail.url }}" alt="Thumbnail">
                    </a>
                    <div class="video-card-info">
                        <strong>{{ thing.title }}</strong>
                        <small>
                            <a href="{% url 'app:account' thing.author %}">{{ authors | get_item:thing.author }}</a>
                            · {{ thing.created_on }}
                        </small>
                    </div> 
                </div>

            {% elif thing.type == "post" %}
                <div class="post-card">
                    <div class="post-card-label">Post - <u><a href="{% url "app:account" thing.author %}">{{ authors | get_item:thing.author }}</a></u></div>
                    
                    <a href="{% url 'app:post' thing.pk %}">
                        <strong>{{ thing.title }}</strong>
                    </a>
                    <p>{{ thing.body | markdown_truncate:100 }}</p>
                    <small>{{ thing.created_on }}</small>
                </div>

            {% endif %}

        {% endfor %}
    </div>
{% else %}
    <p>Nothing posted yet.</p>
{% endif %}

<div id="toast-container"></div>
{% endblock page_content %}

app/templates/app/cornhub.html
{% extends 'css.html' %}

{% block title %}Cornhub{% endblock %}

{% block extra_head %}
<script src="https://player.twitch.tv/js/embed/v1.js"></script>

<!-- Create a Twitch.Player object. This will render within the placeholder div -->
<script type="text/javascript">
  new Twitch.Player("twitch-embed", {
    channel: "4cvit"
  });
</script>
{% endblock extra_head %}

{% block page_content %}
<h1 style="text-align: center">You Sick Fuck</h1>

<div id="toast-container"></div>

<div id="twitch-embed"></div>

<!-- Load the Twitch embed script -->


{% endblock page_content %}

app/templates/app/createVideo.html
{% extends "base.html" %}

{% load static %}

{% block page_content %}
<h1>Post Video</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        {{ form.title }}*
    </div>
    <div>
        {{ form.description }}
    </div>
    <div>
        Thumbnail: {{ form.thumbnail }}
    </div>
    <div>
        Video: {{ form.video_file }}*
    </div>
    <small>* marks a field as required</small><br>
    <button type="submit" class="btn btn-primary">Submit</button>
    <a href="{% url 'app:index' %}">Cancel</a>
</form>

<small>Please note that videos and comments may be deleted, as YubTub is still in development.</small>
{% endblock page_content %}

app/templates/app/following.html
{% extends 'base.html' %}
{% load markdown_truncate dict_extras %}
{% block page_content %}
	<h1>People you Follow</h1>
	<ul>
	{% for account in following %}
		<li><a href="{% url 'app:account' account.id %}">{{ account.username }}</a></li>
	{% endfor %}
	</ul>

	<h1>Videos from people you follow</h1>
{% if combined %}
    <div class="video-grid">
        {% for thing in combined %}

            {% if thing.type == "video" %}
                <div class="video-card">
                    <a href="{% url 'app:watch' thing.id %}">
                        <img src="{{ thing.thumbnail.url }}" alt="Thumbnail">
                    </a>
                    <div class="video-card-info">
                        <strong>{{ thing.title }}</strong>
                        <small>
                            <a href="{% url 'app:account' thing.author %}">{{ authors | get_item:thing.author }}</a>
                            · {{ thing.created_on }}
                        </small>
                    </div> 
                </div>

            {% elif thing.type == "post" %}
                <div class="post-card">
                    <div class="post-card-label">Post - <u><a href="{% url "app:account" thing.author %}">{{ authors | get_item:thing.author }}</a></u></div>
                    
                    <a href="{% url 'app:post' thing.pk %}">
                        <strong>{{ thing.title }}</strong>
                    </a>
                    <p>{{ thing.body | markdown_truncate:100 }}</p>
                    <small>{{ thing.created_on }}</small>
                </div>

            {% endif %}

        {% endfor %}
    </div>
{% else %}
    <p>Nothing posted yet.</p>
{% endif %}
{% endblock page_content %}

{% block extra_navbar %}
<a class="button" href="{% url 'chat:index' %}">Chat</a>
{% endblock %}

app/templates/app/index.html
{% extends "base.html" %}
{% load markdown_truncate dict_extras %}

{% block title %}YubTub - Home{% endblock title %}


{% block page_content %}
    {% if combined %}
    <div class="video-grid">
        {% for thing in combined %}

            {% if thing.type == "video" %}
                <div class="video-card">
                    <a href="{% url 'app:watch' thing.id %}">
                        <img src="{{ thing.thumbnail.url }}" alt="Thumbnail">
                    </a>
                    <div class="video-card-info">
                        <strong>{{ thing.title }}</strong>
                        <small>
                            <a href="{% url 'app:account' thing.author %}">{{ authors | get_item:thing.author }}</a>
                            · {{ thing.created_on }}
                        </small>
                    </div> 
                </div>

            {% elif thing.type == "post" %}
                <div class="post-card">
                    <div class="post-card-label">Post - <u><a href="{% url "app:account" thing.author %}">{{ authors | get_item:thing.author }}</a></u></div>
                    
                    <a href="{% url 'app:post' thing.pk %}">
                        <strong>{{ thing.title }}</strong>
                    </a>
                    <p>{{ thing.body | markdown_truncate:100 }}</p>
                    <small>{{ thing.created_on }}</small>
                </div>

            {% endif %}

        {% endfor %}
    </div>
{% else %}
    <p>Nothing posted yet.</p>
{% endif %}
{% endblock page_content %}

app/templates/app/makePost.html
{% extends "base.html" %}
{% block page_title %}Create Post{% endblock page_title %}

{% block page_content %}
<h1>Create Post</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        {{ form.title }}
    </div>
    <div>
        {{ form.body }}<br>
    <small><a href="{% url 'app:mdHelp' %}">Markdown</a> is supported!</small>
    </div>
    <div>
        <small>Add an image</small>
    	{{ form.images }} <b>(Not Required)</b>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <a href="{% url 'app:index' %}">Cancel</a>
</form>
{% endblock page_content %}

app/templates/app/mdHelp.html
{% extends "css.html" %}
{% load markdown_extras %}
{% load static %}
{% block page_content %}
{{ mdHelp | markdown }}
{% endblock page_content %}

app/templates/app/search.html
{% extends "base.html" %}
{% load markdown_truncate dict_extras %}


{% block page_content %}
<form action="{% url 'app:search' %}" method="get">
  <input name="q" type="text" placeholder="Search...">
</form>
    {% if combined %}
    <div class="video-grid">
        {% for thing in combined %}

            {% if thing.type == "video" %}
                <div class="video-card">
                    <a href="{% url 'app:watch' thing.id %}">
                        <img src="{{ thing.thumbnail.url }}" alt="Thumbnail">
                    </a>
                    <div class="video-card-info">
                        <strong>{{ thing.title }}</strong>
                        <small>
                            <a href="{% url 'app:account' thing.author %}">{{ authors | get_item:thing.author }}</a>
                            · {{ thing.created_on }}
                        </small>
                    </div> 
                </div>

            {% elif thing.type == "post" %}
                <div class="post-card">
                    <div class="post-card-label">Post - <u><a href="{% url "app:account" thing.author %}">{{ authors | get_item:thing.author }}</a></u></div>
                    
                    <a href="{% url 'app:post' thing.pk %}">
                        <strong>{{ thing.title }}</strong>
                    </a>
                    <p>{{ thing.body | markdown_truncate:100 }}</p>
                    <small>{{ thing.created_on }}</small>
                </div>

            {% endif %}

        {% endfor %}
    </div>
{% else %}
    <p>Nothing matching that search query.</p>
{% endif %}

{% endblock page_content %}

app/templates/app/video.html
{% extends "base.html" %}

{% load static %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/widgets.css' %}">
    <script src="{% static 'admin/js/core.js' %}"></script>
    <script src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
    <script src="{% static 'admin/js/jquery.init.js' %}"></script>
    <script src="{% static 'admin/js/calendar.js' %}"></script>
    <script src="{% static 'admin/js/admin/DateTimeShortcuts.js' %}"></script>
{% endblock %}

{% block page_content %}
<h1>Create Recipe</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        {{ form.title }}
    </div>
    <div>
        {{ form.description }}
    </div>
    <div>
        <p>Schedule Post</p>
        {{ form.schedulePost }}
    </div>
    <div>
        Thumbnail: {{ form.thumbnail }}
    </div>
    <div>
        Video: {{ form.video }}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <a href="{% url 'index' %}">Cancel</a>
</form>
{% endblock page_content %}

app/templates/app/viewPost.html
{% extends "base.html" %}
{% load markdown_extras dict_extras %}

{% block page_title %}
    <h2>{{ post.title }}</h2>
{% endblock page_title %}

{% block page_content %}
    <small>
        {{ post.created_on.date }} at {{ post.created_on.time}}
    </small>
    <p>
        By <a href="{% url 'app:account' post.author %}">{{ postAuthor }}</a>
    </p>

    <p>{{ post.body | markdown }}</p>
    <div style="justify-content: center; align-items: center; ">	
    	{% if post.images %}
    	<img src="{{ post.images.url }}" alt="" width="40%" height="auto">
    	{% endif %}
    </div>

	<hr>
    {% if user.is_authenticated and not muted %}
    <h3>Leave a comment:</h3>
    <form method="post">
        {% csrf_token %}
        <div>
            {{ form.body }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endif %}
    <h3>Comments:</h3>
    <div>
    {% for comment in comments %}
        <p>
            On {{ comment.created_on.date }} <b>{{ authors | get_item:comment.author }}</b> wrote:
            <div style="margin-left: 25px;">
                {% if comment.author.username == "admin" %}
                    {{ comment.body | markdown | linebreaks }}
                {% else %}
                    {{ comment.body | linebreaks }}
                    <script>console.log("{{ comment.body }}")</script>
                {% endif %}
            </div>
        </p>
    {% endfor %}
    </div>

{% endblock page_content %}

app/templates/app/watch.html
{% extends "base.html" %}
{% load markdown_extras dict_extras %}
{% block title %}YubTub: {{ videos.title }}{% endblock title %}

{% block page_content %}
<h1>{{ videos.title }}</h1>
Uploaded by <a href="/{% url 'app:account' videos.author %}">{{ videoAuthor }}</a>
<div>
<video width="50%" height="50%" controls Play Pause Seeking Volume Fullscreen>
  <source src="{{ videos.video_file.url }}" type="video/mp4">
  No video support.
</video>
</div>

<div>
<a href="{{ videos.video_file.url }}" class="button">vid</a>
<button id="like-button" data-video-id="{{ pk }}" onclick="likeVideo()">{{ likes }}:&#x1F44D;</button> <small>Views: {{ videos.views }}</small>


{{ videos.description | markdown | linebreaks }}  <!-- linegrapes/ do she pipe it tillyo linegreaps -->
</div>

<div>
	{% if user.is_authenticated and not muted %}
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<div>
			{{ form.body }}
		</div>
		<button type="submit" class="btn btn-primary">Submit</button>
	</form>
	{% endif %}
</div>
{% block comments %}
<h3>Comments:</h3>
{% for comment in comments %}
<p>
    On {{ comment.created_on.date }}, at {{ comment.created_on.time }} <b>{{ authors | get_item:comment.author }}</b> wrote: 
    <div style="margin-left: 25px;">
		{% if comment.author.username == "admin" %}
    		{{ comment.body | markdown | linebreaks }}
		{% else %}
			{{ comment.body | linebreaks }}
		{% endif %}
    </div>
</p>
{% endfor %}
{% endblock comments %}
<div id="toast-container"></div>
{% endblock %}